name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
    name: integration-tests (PHP ${{ matrix.php-versions }})
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
      - name: Run test suite
        run: |
          vendor/bin/phpunit --color tests/
        env:
          OCI_PRIVATE_KEY_URL: ${{ secrets.OCI_PRIVATE_KEY_URL }}
